export const tabConfig = [{
    icon: '&#xe660;',
    name: "首页",
    key: 'home',
    src: `${weex.config.eros.jsServer}/dist/js/pages/yanxuanDemo/home/index.js`,
    visibility: 'visible'
}, {
    icon: '&#xe744;',
    name: "专题",
    key: 'topic',
    src: `${weex.config.eros.jsServer}/dist/js/pages/yanxuanDemo/topic/index.js`,
    visibility: 'hidden'
}, {
    icon: '&#xe605;',
    name: "分类",
    key: 'class',
    src: `${weex.config.eros.jsServer}/dist/js/pages/yanxuanDemo/class/index.js`,
    visibility: 'hidden'
}, {
    icon: '&#xe61a;',
    name: "购物车",
    key: 'shop',
    src: `${weex.config.eros.jsServer}/dist/js/pages/yanxuanDemo/shop/index.js`,
    visibility: 'hidden'
}, {
    icon: '&#xe639;',
    name: "个人",
    key: 'my',
    src: `${weex.config.eros.jsServer}/dist/js/pages/yanxuanDemo/my/index.js`,
    visibility: 'hidden'
}]